// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BurgerMenuBtn: typeof import('./components/app/utils/BurgerMenuBtn.vue')['default']
    CollapseTransition: typeof import('./components/app/utils/CollapseTransition.vue')['default']
    ComponentsDemo: typeof import('./components/app/ComponentsDemo.vue')['default']
    ComponentsDemoItem: typeof import('./components/app/ComponentsDemoItem.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Playground: typeof import('./components/app/Playground.vue')['default']
    PropsDoc: typeof import('./components/app/PropsDoc.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeNode: typeof import('./components/app/utils/TreeNode.vue')['default']
    TreeNode2: typeof import('./components/app/utils/TreeNode2.vue')['default']
    VAlert: typeof import('./components/core/data-display/VAlert/VAlert.vue')['default']
    VAvatar: typeof import('./components/core/data-display/VAvatar/VAvatar.vue')['default']
    VAvatarGroup: typeof import('./components/core/data-display/VAvatar/VAvatarGroup.vue')['default']
    VBadge: typeof import('./components/core/data-display/VBadge/VBadge.vue')['default']
    VBreadcrumb: typeof import('./components/core/navigation/VBreadcrumb/VBreadcrumb.vue')['default']
    VBtn: typeof import('./components/core/inputs/VBtn/VBtn.vue')['default']
    VBtnGroup: typeof import('./components/core/inputs/VBtnGroup/VBtnGroup.vue')['default']
    VCard: typeof import('./components/core/surface/VCard/VCard.vue')['default']
    VCheckbox: typeof import('./components/core/inputs/VCheckbox/VCheckbox.vue')['default']
    VHeader: typeof import('./components/app/layout/VHeader.vue')['default']
    VRadio: typeof import('./components/core/inputs/VRadio/VRadio.vue')['default']
    VSidebar: typeof import('./components/app/layout/VSidebar.vue')['default']
    VTextField: typeof import('./components/core/inputs/VTextField/VTextField.vue')['default']
  }
}

export {}
